// app/sitemap.ts
import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://ai-autosite.com'
  
  // Tool category pages
  const toolCategories = [
    'converters',
    'editors',
    'image-tools',
    'generators',
    'analyzers',
    'ai-tools',
    'dev-tools',
    'learning',
    'audio-tools'
  ]
  
  const tools = [
    'age-calculator',
    'ai-dev-dictionary',
    'ai-project-visualizer',
    'ai-prompt-generator',
    'ai-resume',
    'ai-summarizer',
    'aspect-ratio-calculator',
    'base64',
    'bg-eraser',
    'blurtap',
    'bmi-calculator',
    'code-dependency-visualizer',
    'code-formatter',
    'code-roaster',
    'color-palette',
    'competitive-analyzer',
    'cornell-note',
    'countdown-timer',
    'cron-generator',
    'debate-trainer',
    'diff-checker',
    'favicon-generator',
    'gradient-generator',
    'haiku-generator',
    'hash-generator',
    'hashtag-generator',
    'image-compress',
    'image-grid-maker',
    'image-splitter',
    'instagram-bio',
    'japanese-ocr',
    'json-csv',
    'json-format',
    'lorem-ipsum',
    'markdown-html',
    'meta-tag-generator',
    'network-checker',
    'password-generator',
    'pc-optimizer',
    'pdf-summarizer',
    'pdf-test-generator', 
    'pdf-to-data',
    'pdf-tools',
    'percentage-calculator',
    'pomodoro-timer',
    'qr-code',
    'regex-tester',
    'spam-email-checker',
    'stack-recommender',
    'tech-stack-analyzer',
    'test-file-generator',
    'test-image-generator',
    'test-text-generator',
    'text-case',
    'text-counter',
    'timestamp-converter',
    'token-compressor',
    'twitter-counter',
    'unit-converter',
    'url-encoder',
    'uuid-generator',
    'voice-transcription',
    'whatsapp-link',
    'word-counter-pro'
  ]

  const blogPosts = [
    'age-calculator-guide',
    'ai-dev-dictionary',
    'ai-project-visualizer-guide',
    'ai-prompt-generator-guide',
    'ai-resume-generator',
    'ai-stack-recommender-guide',
    'ai-summarizer-guide',
    'aspect-ratio-calculator-guide',
    'base64-guide',
    'blurtap-guide',
    'bmi-calculator-guide',
    'choosing-the-right-tech-stack',
    'code-dependency-visualizer',
    'code-formatter-guide',
    'code-roaster-guide',
    'color-palette-guide',
    'competitive-analyzer-guide',
    'cornell-note-guide',
    'countdown-timer-guide',
    'cron-generator-guide',
    'debate-trainer-guide',
    'diff-checker-guide',
    'favicon-generator-guide',
    'gradient-generator-guide',
    'haiku-generator-guide',
    'hash-generator-guide',
    'hashtag-generator-guide',
    'how-to-use-code-roaster',
    'image-compress-guide',
    'image-grid-maker-guide',
    'image-splitter-guide',
    'instagram-bio-guide',
    'japanese-ocr-guide',
    'json-beautify-guide',
    'json-csv-converter-guide',
    'lorem-ipsum-generator-guide',
    'markdown-guide',
    'meta-tag-generator-guide',
    'network-checker-guide',
    'password-generator-guide',
    'pc-optimizer-guide',
    'pdf-summarizer-guide',
    'pdf-test-generator-guide',
    'pdf-to-data-guide',
    'pdf-tools-guide',
    'percentage-calculator-guide',
    'pomodoro-timer-guide',
    'privacy-in-development',
    'qr-code-guide',
    'regex-tester-guide',
    'spam-email-checker-guide',
    'test-file-generator-guide',
    'test-image-generator-guide',
    'test-text-generator-guide',
    'text-case-converter',
    'text-counter-guide',
    'timestamp-converter-guide',
    'token-compressor-guide',
    'twitter-counter-guide',
    'unit-converter-guide',
    'url-encoder-guide',
    'uuid-generator-guide',
    'voice-transcription-guide',
    'whatsapp-link-generator-guide',
    'word-counter-pro-guide'
  ]

  const highPriorityTools = [
    'ai-dev-dictionary',
    'ai-project-visualizer',
    'ai-prompt-generator',
    'ai-resume',
    'ai-summarizer',
    'bg-eraser',
    'code-roaster',
    'competitive-analyzer',
    'cornell-note',
    'debate-trainer',
    'image-compress',
    'network-checker',
    'pdf-summarizer',
    'pdf-tools',
    'pomodoro-timer',
    'spam-email-checker',
    'stack-recommender',
    'tech-stack-analyzer',
    'voice-transcription'
  ]
  
  return [
    // Homepage
    {
      url: baseUrl,
      lastModified: new Date(),
      changeFrequency: 'daily' as const,
      priority: 1.0,
    },
    
    // Main pages
    {
      url: `${baseUrl}/tools`,
      lastModified: new Date(),
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/blog`,
      lastModified: new Date(),
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },

    // Tool category pages
    ...toolCategories.map(category => ({
      url: `${baseUrl}/tools/${category}`,
      lastModified: new Date(),
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    })),

    // Individual tools
    ...tools.map(tool => ({
      url: `${baseUrl}/tools/${tool}`,
      lastModified: new Date(),
      changeFrequency: 'weekly' as const,
      priority: highPriorityTools.includes(tool) ? 0.9 : 0.7,
    })),

    // Blog posts
    ...blogPosts.map(slug => ({
      url: `${baseUrl}/blog/${slug}`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.6,
    }))
  ]
}