// app/lib/categories/ai-tools.ts
import type { Tool } from './types'

export const aiTools: Tool[] = [
  // ビジネス系AI
  {
    id: 'ai-resume',
    name: 'AI Resume & Cover Letter',
    description: 'Generate professional resumes and cover letters with AI.',
    category: 'ai-tools',
    icon: '📝',
    emoji: '💼',
    color: 'from-indigo-500 to-blue-600',
    status: 'live',
    url: '/tools/ai-resume',
    tags: ['Resume', 'Cover Letter', 'AI', 'Career', 'Claude'],
    difficulty: 'Simple',
    timeToUse: '2 minutes',
    featured: true,
    new: true,
    badge: 'AI',
    pricing: 'freemium',
    apiRequired: true,
    dataProcessing: 'server',
    lastUpdated: '2025-08',
  },
  {
    id: 'ai-prompt-generator',
    name: 'AI Prompt Generator',
    description: 'Create effective prompts for ChatGPT and Claude',
    category: 'ai-tools',
    icon: '🤖',
    color: 'from-purple-500 to-indigo-500',
    url: '/tools/ai-prompt-generator',
    status: 'live',
    badge: 'AI',
    tags: ['ai', 'prompt', 'chatgpt', 'claude', 'generator'],
    difficulty: 'Simple',
    timeToUse: '1 minute',
    featured: true,
    new: true,
    apiRequired: true,
  },
  {
    id: 'spam-email-checker',
    name: 'Spam Email Checker',
    description: 'Check suspicious emails before opening. Detect phishing & typosquatting.',
    category: 'ai-tools',
    icon: '🛡️',
    emoji: '🛡️',
    color: 'from-red-500 to-orange-500',
    status: 'live',
    url: '/tools/spam-email-checker',
    tags: ['email', 'spam', 'phishing', 'security', 'safety', 'fraud', 'privacy', 'AI'],
    difficulty: 'Instant',
    timeToUse: '10 seconds',
    featured: true,
    new: true,
    badge: 'AI',
    apiRequired: true,
    dataProcessing: 'server',
    pricing: 'freemium',
    lastUpdated: '2025-10-18',
  },
  {
    id: 'ai-summarizer',
    name: 'AI Text Summarizer',
    description: 'Transform lengthy content into concise summaries with AI.',
    category: 'ai-tools',
    icon: '✨',
    emoji: '📄',
    color: 'from-purple-500 to-pink-500',
    status: 'live',
    url: '/tools/ai-summarizer',
    tags: ['AI', 'Summary', 'Text', 'Study', 'Productivity'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: true,
    new: true,
    badge: 'AI',
    pricing: 'freemium',
    apiRequired: true,
    dataProcessing: 'server',
    lastUpdated: '2025-08',
  },
  {
    id: 'pdf-summarizer',
    name: 'PDF Summarizer',
    description: 'AI-powered PDF summary generator for quick study reviews.',
    category: 'ai-tools',
    icon: '📄',
    color: 'from-green-500 to-teal-500',
    status: 'live',
    url: '/tools/pdf-summarizer',
    tags: ['pdf', 'summary', 'study', 'ai'],
    difficulty: 'Simple',
    timeToUse: '2 minutes',
    featured: true,
    new: true,
    badge: 'AI',
    pricing: 'freemium',
    apiRequired: true,
    dataProcessing: 'hybrid',
    dependencies: ['pdfjs-dist'],
  },
  {
    id: 'pdf-to-data',
    name: 'PDF to CSV/Excel',
    description: 'Extract tables from PDFs. AI-powered CSV or Excel conversion.',
    category: 'ai-tools',
    icon: '📊',
    emoji: '📊',
    color: 'from-emerald-500 to-teal-500',
    status: 'live',
    url: '/tools/pdf-to-data',
    tags: ['PDF', 'CSV', 'Excel', 'Data', 'AI', 'Extraction'],
    difficulty: 'Simple',
    timeToUse: '1 minute',
    featured: true,
    new: true,
    badge: 'AI',
    pricing: 'freemium',
    apiRequired: true,
    dataProcessing: 'server',
    dependencies: ['openai', 'xlsx'],
    lastUpdated: '2025-09',
  },
  {
    id: 'debate-trainer',
    name: 'Debate Trainer',
    description: 'Practice argumentation skills with AI opponents. Get feedback.',
    category: 'ai-tools',
    icon: '⚔️',
    emoji: '💬',
    color: 'from-purple-500 to-pink-500',
    status: 'live',
    url: '/tools/debate-trainer',
    tags: ['debate', 'argumentation', 'critical thinking', 'AI', 'practice'],
    difficulty: 'Intermediate',
    timeToUse: '15 minutes',
    featured: true,
    new: true,
    badge: 'AI',
    pricing: 'freemium',
    apiRequired: true,
    dataProcessing: 'server',
    dependencies: ['openai'],
    lastUpdated: '2025-09',
  },
  {
    id: 'ai-project-visualizer',
    name: 'AI Project Visualizer',
    description: 'Transform file structure into AI-shareable diagrams.',
    category: 'ai-tools',
    icon: '🗂️',
    emoji: '🌳',
    color: 'from-cyan-500 to-purple-500',
    status: 'live',
    url: '/tools/ai-project-visualizer',
    tags: ['visualization', 'AI', 'project', 'mermaid', 'diagram'],
    difficulty: 'Simple',
    timeToUse: '1 minute',
    featured: false,
    new: false,
    badge: 'AI',
    pricing: 'free',
    dataProcessing: 'local',
    lastUpdated: '2025-10',
  },
  {
    id: 'stack-recommender',
    name: 'Stack Recommender',
    description: 'Get AI-powered tech stack recommendations for your project.',
    category: 'ai-tools',
    icon: '🤖',
    color: 'from-violet-500 to-purple-600',
    status: 'live',
    badge: 'AI',
    url: '/tools/stack-recommender',
    tags: ['AI', 'Planning', 'Recommendations', 'stack', 'tech'],
    difficulty: 'Intermediate',
    timeToUse: '3 minutes',
    featured: false,
    new: true,
    apiRequired: true,
    pricing: 'freemium',
    dataProcessing: 'server',
  },
    {
    id: 'haiku-generator',
    name: 'AI Haiku Generator',
    description: 'Learn poetry writing through haiku. Master 5-7-5 structure.',
    category: 'ai-tools',
    icon: '🌸',
    color: 'from-pink-500 to-purple-500',
    status: 'live',
    badge: 'AI',
    url: '/tools/haiku-generator',
    tags: ['haiku', 'poetry', 'writing', 'AI', 'learning', 'creative'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    new: true,
    apiRequired: true,
    pricing: 'free',
    dataProcessing: 'hybrid',
  },
  {
    id: 'code-roaster',
    name: 'Code Roaster',
    description: 'AI-powered code review tool with humor. Get roasted!',
    category: 'ai-tools',
    icon: '🔥',
    color: 'from-orange-500 to-red-500',
    status: 'live',
    url: '/tools/code-roaster',
    tags: ['code review', 'ai', 'debugging', 'learning'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: true,
    new: true,
    badge: 'AI',
    pricing: 'free',
    apiRequired: true,
    dataProcessing: 'server',
  },
]