// app/lib/categories/analyzers.ts
import type { Tool } from './types'

export const analyzers: Tool[] = [
  {
    id: 'pc-optimizer',
    name: 'PC Optimizer Advisor',
    description: 'Free up storage space! Analyze Program Files for removal.',
    category: 'analyzers',
    icon: '💻',
    emoji: '💻',
    color: 'from-blue-500 to-cyan-500',
    status: 'live',
    url: '/tools/pc-optimizer',
    tags: ['Windows', 'Performance', 'Cleanup', 'optimize', 'storage'],
    difficulty: 'Simple',
    timeToUse: '3 minutes',
    featured: true,
    new: true,
    pricing: 'free',
    dataProcessing: 'local',
    lastUpdated: '2025-01',
  },
  {
    id: 'network-checker',
    name: 'Network Checker',
    description: 'Find why devices can\'t connect. Simple network troubleshooting.',
    category: 'analyzers',
    icon: '🌐',
    emoji: '🌐',
    color: 'from-cyan-500 to-blue-600',
    status: 'live',
    url: '/tools/network-checker',
    tags: ['network', 'troubleshoot', 'ip', 'connection', 'lan', 'diagnose'],
    difficulty: 'Simple',
    timeToUse: '1 minute',
    featured: false,
    new: true,
    badge: 'NEW',
    pricing: 'free',
    dataProcessing: 'local',
    lastUpdated: '2025-10',
  },
  {
    id: 'token-compressor',
    name: 'AI Token Compressor',
    description: 'Compress files for AI sharing. Reduce API costs by 70%.',
    category: 'analyzers',
    icon: '🗜️',
    emoji: '💰',
    color: 'from-cyan-500 to-blue-600',
    status: 'live',
    url: '/tools/token-compressor',
    tags: ['token', 'compression', 'AI', 'optimization', 'ChatGPT', 'Claude', 'analyze'],
    difficulty: 'Simple',
    timeToUse: '2 minutes',
    featured: true,
    new: true,
    pricing: 'free',
    apiRequired: false,
    dataProcessing: 'local',
    lastUpdated: '2025-09',
    dependencies: ['tiktoken', 'jszip', 'file-saver'],
  },
  {
    id: 'competitive-analyzer',
    name: 'Competitive Analyzer',
    description: 'Analyze competitors and market trends',
    category: 'analyzers',
    icon: '📊',
    color: 'from-blue-500 to-purple-500',
    url: '/tools/competitive-analyzer',
    status: 'live',
    tags: ['analysis', 'competitor', 'market', 'business'],
    difficulty: 'Intermediate',
    timeToUse: '5 minutes',
    featured: false,
    new: true,
  },
  {
    id: 'japanese-ocr',
    name: 'Japanese OCR & Translation',
    description: 'Extract and translate Japanese text from images instantly.',
    category: 'analyzers',
    icon: '🇯🇵',
    color: 'from-red-500 to-pink-500',
    status: 'live',
    url: '/tools/japanese-ocr',
    tags: ['ocr', 'japanese', 'translation', 'text-extraction', 'image-to-text', 'analyze'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: true,
    new: true,
    pricing: 'free',
    apiRequired: false,
    dataProcessing: 'local',
  },
]