// app/lib/categories/audio-tools.ts
import type { Tool } from './types'

export const audioTools: Tool[] = [
  // ========================================
  // Live Tools
  // ========================================
  {
    id: 'voice-transcription',
    name: 'Voice Transcription',
    description: 'Convert speech to text with AI. 100% browser-based, private, and free.',
    category: 'audio-tools',
    icon: '🎤',
    emoji: '🎙️',
    color: 'from-violet-500 to-purple-600',
    status: 'live',
    url: '/tools/voice-transcription',
    tags: ['transcription', 'speech-to-text', 'audio', 'whisper', 'AI', 'privacy', 'offline'],
    difficulty: 'Simple',
    timeToUse: '1 minute',
    featured: true,
    new: false,
    pricing: 'free',
    apiRequired: false,
    dataProcessing: 'local',
    lastUpdated: '2025-12',
  },
  {
    id: 'mp3-to-wav',
    name: 'MP3 to WAV',
    description: 'Convert MP3 files to high-quality WAV format. Choose 16, 24, or 32-bit output.',
    category: 'audio-tools',
    icon: '🔄',
    emoji: '🔄',
    color: 'from-blue-500 to-cyan-500',
    status: 'live',
    url: '/tools/mp3-to-wav',
    tags: ['converter', 'mp3', 'wav', 'audio', 'format', 'privacy'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: false,
    new: true,
    badge: 'NEW',
    pricing: 'free',
    apiRequired: false,
    dataProcessing: 'local',
    lastUpdated: '2025-12',
  },
  {
    id: 'wav-to-mp3',
    name: 'WAV to MP3',
    description: 'Compress WAV files to MP3 format. Reduce file size by up to 90%.',
    category: 'audio-tools',
    icon: '🔄',
    emoji: '🔄',
    color: 'from-blue-500 to-cyan-500',
    status: 'live',
    url: '/tools/wav-to-mp3',
    tags: ['converter', 'wav', 'mp3', 'audio', 'compress', 'privacy'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: false,
    new: true,
    badge: 'NEW',
    pricing: 'free',
    apiRequired: false,
    dataProcessing: 'local',
    lastUpdated: '2025-12',
  },
  {
    id: 'volume-booster',
    name: 'Volume Booster',
    description: 'Make quiet audio louder or reduce volume. Includes auto-normalize feature.',
    category: 'audio-tools',
    icon: '🔊',
    emoji: '🔊',
    color: 'from-amber-500 to-orange-500',
    status: 'live',
    url: '/tools/volume-booster',
    tags: ['volume', 'amplify', 'normalize', 'audio', 'fix', 'privacy'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: false,
    new: true,
    badge: 'NEW',
    pricing: 'free',
    apiRequired: false,
    dataProcessing: 'local',
    lastUpdated: '2025-12',
  },
  {
    id: 'record-voice',
    name: 'Record Voice',
    description: 'Record audio from your microphone. Download as WAV or MP3.',
    category: 'audio-tools',
    icon: '🎙️',
    emoji: '🎙️',
    color: 'from-pink-500 to-rose-500',
    status: 'live',
    url: '/tools/record-voice',
    tags: ['recorder', 'microphone', 'voice', 'audio', 'capture', 'privacy'],
    difficulty: 'Simple',
    timeToUse: 'Varies',
    featured: false,
    new: true,
    badge: 'NEW',
    pricing: 'free',
    apiRequired: false,
    dataProcessing: 'local',
    lastUpdated: '2025-12',
  },

  // ========================================
  // Coming Soon Tools
  // ========================================
  {
    id: 'audio-converter',
    name: 'Audio Converter',
    description: 'Convert between audio formats: MP3, WAV, OGG, FLAC, M4A, and more.',
    category: 'audio-tools',
    icon: '🔄',
    emoji: '🔄',
    color: 'from-blue-500 to-cyan-500',
    status: 'live',
    url: '/tools/audio-converter',
    tags: ['converter', 'format', 'audio', 'mp3', 'wav', 'ogg', 'flac'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: false,
    new: true,
    badge: 'NEW',
    pricing: 'free',
    apiRequired: false,
    dataProcessing: 'local',
    lastUpdated: '2025-12',
  },
  {
    id: 'trim-audio',
    name: 'Trim Audio',
    description: 'Cut and trim audio files. Remove unwanted parts from the beginning or end.',
    category: 'audio-tools',
    icon: '✂️',
    emoji: '✂️',
    color: 'from-emerald-500 to-green-500',
    status: 'live',
    url: '/tools/trim-audio',
    tags: ['trim', 'cut', 'edit', 'audio', 'clip'],
    difficulty: 'Simple',
    timeToUse: '1 minute',
    featured: false,
    new: true,
    badge: 'NEW',
    pricing: 'free',
    apiRequired: false,
    dataProcessing: 'local',
    lastUpdated: '2025-12',
  },
  {
    id: 'speed-changer',
    name: 'Speed Changer',
    description: 'Speed up or slow down audio playback. Adjust from 0.25x to 4x speed.',
    category: 'audio-tools',
    icon: '⏩',
    emoji: '⏩',
    color: 'from-amber-500 to-orange-500',
    status: 'live',
    url: '/tools/speed-changer',
    tags: ['speed', 'tempo', 'playback', 'audio', 'adjust'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: false,
    new: true,
    badge: 'NEW',
    pricing: 'free',
    apiRequired: false,
    dataProcessing: 'local',
    lastUpdated: '2025-12',
  },
  {
    id: 'merge-audio',
    name: 'Merge Audio',
    description: 'Combine multiple audio files into one. Add crossfade between tracks.',
    category: 'audio-tools',
    icon: '🔗',
    emoji: '🔗',
    color: 'from-emerald-500 to-green-500',
    status: 'live',
    url: '/tools/merge-audio',
    tags: ['merge', 'combine', 'join', 'audio', 'concatenate'],
    difficulty: 'Medium',
    timeToUse: '2 minutes',
    featured: false,
    new: true,
    badge: 'NEW',
    pricing: 'free',
    apiRequired: false,
    dataProcessing: 'local',
    lastUpdated: '2025-12',
  },
  {
    id: 'extract-audio',
    name: 'Extract Audio',
    description: 'Extract audio track from video files. Supports MP4, WebM, MOV.',
    category: 'audio-tools',
    icon: '🎬',
    emoji: '🎬',
    color: 'from-pink-500 to-rose-500',
    status: 'live',
    url: '/tools/extract-audio',
    tags: ['extract', 'video', 'audio', 'rip', 'convert'],
    difficulty: 'Simple',
    timeToUse: '1 minute',
    featured: false,
    new: true,
    badge: 'NEW',
    pricing: 'free',
    apiRequired: false,
    dataProcessing: 'local',
    lastUpdated: '2025-12',
  },
  {
    id: 'reverse-audio',
    name: 'Reverse Audio',
    description: 'Play audio backwards. Create reverse sound effects.',
    category: 'audio-tools',
    icon: '⏪',
    emoji: '⏪',
    color: 'from-emerald-500 to-green-500',
    status: 'live',
    url: '/tools/reverse-audio',
    tags: ['reverse', 'backwards', 'effect', 'audio'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: false,
    new: true,
    badge: 'NEW',
    pricing: 'free',
    apiRequired: false,
    dataProcessing: 'local',
    lastUpdated: '2025-12',
  },
  {
    id: 'fade-audio',
    name: 'Fade Audio',
    description: 'Add fade in and fade out effects to audio files.',
    category: 'audio-tools',
    icon: '📈',
    emoji: '📈',
    color: 'from-emerald-500 to-green-500',
    status: 'live',
    url: '/tools/fade-audio',
    tags: ['fade', 'effect', 'transition', 'audio'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: false,
    new: true,
    badge: 'NEW',
    pricing: 'free',
    apiRequired: false,
    dataProcessing: 'local',
    lastUpdated: '2025-12',
  },
  {
    id: 'loop-audio',
    name: 'Loop Audio',
    description: 'Create seamless audio loops. Perfect for music and sound effects.',
    category: 'audio-tools',
    icon: '🔁',
    emoji: '🔁',
    color: 'from-emerald-500 to-green-500',
    status: 'live',
    url: '/tools/loop-audio',
    tags: ['loop', 'repeat', 'seamless', 'audio', 'music'],
    difficulty: 'Simple',
    timeToUse: '1 minute',
    featured: false,
    new: true,
    badge: 'NEW',
    pricing: 'free',
    apiRequired: false,
    dataProcessing: 'local',
    lastUpdated: '2025-12',
  },
  {
    id: 'text-to-audio',
    name: 'Text to Audio',
    description: 'Convert text to speech. Generate natural-sounding audio from text.',
    category: 'audio-tools',
    icon: '🗣️',
    emoji: '🗣️',
    color: 'from-pink-500 to-rose-500',
    status: 'live',
    url: '/tools/text-to-audio',
    tags: ['tts', 'text-to-speech', 'voice', 'synthesis', 'audio'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: false,
    new: true,
    badge: 'NEW',
    pricing: 'free',
    apiRequired: false,
    dataProcessing: 'local',
    lastUpdated: '2025-12',
  },
]

// ========================================
// Helper Functions
// ========================================

/**
 * Get all live audio tools
 */
export function getLiveAudioTools(): Tool[] {
  return audioTools.filter(tool => tool.status === 'live');
}

/**
 * Get all coming soon audio tools
 */
export function getComingAudioTools(): Tool[] {
  return audioTools.filter(tool => tool.status === 'coming');
}

/**
 * Get audio tools by tag
 */
export function getAudioToolsByTag(tag: string): Tool[] {
  return audioTools.filter(tool => tool.tags?.includes(tag));
}

/**
 * Get converter tools
 */
export function getConverterTools(): Tool[] {
  return audioTools.filter(tool => tool.tags?.includes('converter'));
}

/**
 * Get editor tools
 */
export function getEditorTools(): Tool[] {
  return audioTools.filter(tool => 
    tool.tags?.some(tag => ['trim', 'cut', 'merge', 'fade', 'loop', 'reverse'].includes(tag))
  );
}
