// app/lib/categories/business-tools.ts
import type { Tool } from './types'

export const businessTools: Tool[] = [
  {
    id: 'hashtag-generator',
    name: 'Hashtag Generator',
    description: 'Generate perfect hashtags for social media instantly',
    category: 'business',
    icon: '#️⃣',
    color: 'from-pink-500 to-purple-500',
    status: 'live',
    url: '/tools/hashtag-generator',
    tags: ['hashtag', 'social-media', 'instagram', 'twitter', 'marketing'],
    difficulty: 'Instant',
    timeToUse: '5 seconds',
    featured: true,
    new: true,
    badge: 'HOT',
  },
  {
    id: 'whatsapp-link',
    name: 'WhatsApp Link Generator',
    description: 'Create click-to-chat links for business',
    category: 'business',
    icon: '💬',
    color: 'from-green-500 to-emerald-500',
    url: '/tools/whatsapp-link',
    status: 'live',
    tags: ['whatsapp', 'link', 'business', 'chat', 'generator'],
    difficulty: 'Instant',
    timeToUse: '10 seconds',
    featured: true,
    new: true,
    badge: 'HOT',
  },
  {
    id: 'ai-prompt-generator',
    name: 'AI Prompt Generator',
    description: 'Create effective prompts for ChatGPT and Claude',
    category: 'business',
    icon: '🤖',
    color: 'from-purple-500 to-indigo-500',
    url: '/tools/ai-prompt-generator',
    status: 'live',
    tags: ['ai', 'prompt', 'chatgpt', 'claude', 'generator'],
    difficulty: 'Simple',
    timeToUse: '1 minute',
    featured: true,
    new: true,
    badge: 'HOT',
    apiRequired: true,
  },
  {
    id: 'ai-resume',
    name: 'AI Resume & Cover Letter',
    description: 'Generate professional resumes and cover letters with AI.',
    category: 'business',
    icon: '📝',
    emoji: '💼',
    color: 'from-indigo-500 to-blue-600',
    status: 'live',
    url: '/tools/ai-resume',
    tags: ['Resume', 'Cover Letter', 'AI', 'Career', 'Claude'],
    difficulty: 'Simple',
    timeToUse: '2 minutes',
    featured: true,
    new: true,
    badge: 'AI',
    pricing: 'freemium',
    apiRequired: true,
    dataProcessing: 'server',
    lastUpdated: '2025-01',
  },
]
