// app/lib/categories/converters.ts
import type { Tool } from './types'

export const converters: Tool[] = [
  // データ変換
  {
    id: 'markdown-html',
    name: 'Markdown to HTML',
    description: 'Convert Markdown to HTML with live preview. GitHub Flavored supported.',
    category: 'converters',
    icon: '📄',
    emoji: '📄',
    color: 'from-gray-600 to-gray-800',
    status: 'live',
    url: '/tools/markdown-html',
    tags: ['markdown', 'html', 'converter', 'preview', 'developer'],
    difficulty: 'Simple',
    timeToUse: '10 seconds',
    featured: false,
    pricing: 'free',
    dataProcessing: 'local',
  },
  {
    id: 'json-csv',
    name: 'JSON to CSV Converter',
    description: 'Convert between JSON and CSV formats easily',
    category: 'converters',
    icon: '📄',
    color: 'from-purple-500 to-indigo-500',
    url: '/tools/json-csv',
    status: 'live',
    tags: ['json', 'csv', 'converter', 'data', 'api'],
    difficulty: 'Simple',
    timeToUse: '10 seconds',
    featured: false,
    new: true,
    badge: 'NEW',
  },
  {
    id: 'json-format',
    name: 'JSON Beautify',
    description: 'Format, validate, and minify JSON data instantly.',
    category: 'converters',
    icon: '{ }',
    emoji: '🔧',
    color: 'from-green-500 to-emerald-500',
    status: 'live',
    url: '/tools/json-format',
    tags: ['Data', 'Format', 'Quick', 'json', 'beautify'],
    difficulty: 'Instant',
    timeToUse: '5 seconds',
    featured: false,
    pricing: 'free',
    dataProcessing: 'local',
  },
  {
    id: 'base64',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode and decode Base64 strings. Text and file conversion.',
    category: 'converters',
    icon: '🔐',
    emoji: '🔐',
    color: 'from-green-500 to-teal-500',
    status: 'live',
    url: '/tools/base64',
    tags: ['base64', 'encode', 'decode', 'converter', 'developer'],
    difficulty: 'Simple',
    timeToUse: '5 seconds',
    featured: false,
    pricing: 'free',
    dataProcessing: 'local',
  },
  {
    id: 'text-case',
    name: 'Text Case Converter',
    description: 'Convert text between uppercase, lowercase, title case instantly.',
    category: 'converters',
    icon: '🔤',
    color: 'from-pink-500 to-rose-500',
    status: 'live',
    url: '/tools/text-case',
    tags: ['Text', 'Format', 'Convert', 'case', 'uppercase', 'lowercase'],
    difficulty: 'Instant',
    timeToUse: '3 seconds',
    featured: false,
    pricing: 'free',
    dataProcessing: 'local',
  },
  
  // メディア変換
  {
    id: 'youtube-thumbnail',
    name: 'YouTube Thumbnail Downloader',
    description: 'Download video thumbnails in HD quality',
    category: 'converters',
    icon: '📹',
    color: 'from-red-500 to-pink-500',
    status: 'live',
    url: '/tools/youtube-thumbnail',
    tags: ['youtube', 'thumbnail', 'download', 'video'],
    difficulty: 'Instant',
    timeToUse: '5 seconds',
    featured: true,
    new: true,
  },
  {
    id: 'whatsapp-link',
    name: 'WhatsApp Link Generator',
    description: 'Create click-to-chat links for business',
    category: 'converters',
    icon: '💬',
    color: 'from-green-500 to-emerald-500',
    url: '/tools/whatsapp-link',
    status: 'live',
    tags: ['whatsapp', 'link', 'business', 'chat', 'generator'],
    difficulty: 'Instant',
    timeToUse: '10 seconds',
    featured: true,
    new: true,
    badge: 'HOT',
  },

  // 計算ツール
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert between various units of measurement instantly.',
    category: 'converters',
    icon: '📏',
    emoji: '📏',
    color: 'from-green-500 to-emerald-500',
    status: 'live',
    url: '/tools/unit-converter',
    tags: ['convert', 'units', 'measurement', 'calculator'],
    difficulty: 'Simple',
    timeToUse: '10 seconds',
    featured: false,
    pricing: 'free',
    dataProcessing: 'local',
  },
  {
    id: 'age-calculator',
    name: 'Age Calculator',
    description: 'Calculate exact age in years, months, and days',
    category: 'converters',
    icon: '🎂',
    color: 'from-cyan-500 to-blue-500',
    url: '/tools/age-calculator',
    status: 'live',
    tags: ['age', 'birthday', 'calculator', 'date'],
    difficulty: 'Instant',
    timeToUse: '5 seconds',
    featured: false,
    new: true,
    badge: 'NEW',
  },
  {
    id: 'bmi-calculator',
    name: 'BMI Calculator',
    description: 'Calculate Body Mass Index and health status',
    category: 'converters',
    icon: '⚖️',
    color: 'from-cyan-500 to-blue-500',
    url: '/tools/bmi-calculator',
    status: 'live',
    tags: ['bmi', 'health', 'weight', 'calculator'],
    difficulty: 'Instant',
    timeToUse: '10 seconds',
    featured: false,
    new: true,
    badge: 'NEW',
  },
  {
    id: 'percentage-calculator',
    name: 'Percentage Calculator',
    description: 'Quick percentage calculations for any scenario',
    category: 'converters',
    icon: '%',
    color: 'from-cyan-500 to-blue-500',
    url: '/tools/percentage-calculator',
    status: 'live',
    tags: ['percentage', 'calculator', 'math', 'discount'],
    difficulty: 'Instant',
    timeToUse: '5 seconds',
    featured: false,
    new: true,
  },

  // カウントツール
  {
    id: 'text-counter',
    name: 'Text Counter',
    description: 'Count words, characters, sentences instantly for writers.',
    category: 'converters',
    icon: '📝',
    emoji: '📝',
    color: 'from-blue-500 to-cyan-500',
    status: 'live',
    url: '/tools/text-counter',
    tags: ['text', 'counter', 'words', 'characters', 'writing'],
    difficulty: 'Instant',
    timeToUse: '5 seconds',
    featured: false,
    pricing: 'free',
    dataProcessing: 'local',
  },
  {
    id: 'twitter-counter',
    name: 'Twitter Counter',
    description: 'Count characters for Twitter/X posts in real-time',
    category: 'converters',
    icon: '🐦',
    color: 'from-cyan-500 to-blue-500',
    url: '/tools/twitter-counter',
    status: 'live',
    tags: ['twitter', 'x', 'character', 'counter', 'social'],
    difficulty: 'Instant',
    timeToUse: '1 second',
    featured: false,
    new: true,
  },
]