// app/lib/categories/creative-tools.ts
import type { Tool } from './types'

export const creativeTools: Tool[] = [
  {
    id: 'photocraf',
    name: 'PhotoCraf Editor',
    description: 'Professional photo editor with AI features. Under development.',
    category: 'creative',
    icon: '🖼️',
    emoji: '🖼️',
    color: 'from-purple-600 to-pink-600',
    status: 'coming',
    badge: 'COMING SOON',
    url: '/tools/photocraf',
    tags: ['photo', 'editor', 'AI', 'filters', 'professional'],
    difficulty: 'Advanced',
    timeToUse: '5-10 minutes',
    featured: false,
    pricing: 'freemium',
    dataProcessing: 'hybrid',
    lastUpdated: '2025-01'
  },
{
  id: 'competitive-analyzer',
  name: 'Competitive Analyzer',
  description: 'AI-powered market research to analyze competition and find opportunities.',
  category: 'business-tools',
  icon: '📊',
  emoji: '🎯',
  color: 'from-cyan-500 to-blue-500',
  status: 'live',
  url: '/tools/competitive-analyzer',
  tags: ['market-research', 'competition', 'analysis', 'ai', 'business', 'strategy'],
  difficulty: 'Simple',
  timeToUse: '30 seconds',
  featured: true,
  new: true,
  badge: 'HOT',
  apiRequired: true,
  pricing: 'freemium',
  dataProcessing: 'server',
  dependencies: [],
  configRequired: false,
  lastUpdated: '2025-01',
  projectSource: 'AI Business Tools Suite'
},
{
  id: 'hashtag-generator',
  name: 'Hashtag Generator',
  description: 'Generate perfect hashtags for Instagram, Twitter, and TikTok. Get 30 relevant tags instantly.',
  category: 'business-tools',
  icon: '#️⃣',
  emoji: '🏷️',
  color: 'from-pink-500 to-purple-500',
  status: 'live',
  url: '/tools/hashtag-generator',
  tags: ['hashtag', 'social-media', 'instagram', 'twitter', 'tiktok', 'marketing', 'tags'],
  difficulty: 'Instant',
  timeToUse: '5 seconds',
  featured: true,
  new: true,
  badge: 'HOT',
  apiRequired: false,
  pricing: 'free',
  dataProcessing: 'local',
  dependencies: [],
  configRequired: false,
  lastUpdated: '2025-01',
  projectSource: 'Social Media Tools Suite'
},
{
  id: 'instagram-bio',
  name: 'Instagram Bio Generator',
  description: 'Create perfect profile bios that attract followers',
  category: 'creative',
  icon: '📱',
  color: 'from-pink-500 to-purple-600',
  url: '/tools/instagram-bio',
  status: 'live',
  tags: ['instagram', 'bio', 'social', 'profile', 'generator'],
  difficulty: 'Simple',
  timeToUse: '2 minutes',
  featured: true,
  new: true,
  badge: 'HOT',
},
{
  id: 'youtube-thumbnail',
  name: 'YouTube Thumbnail Downloader',
  description: 'Download video thumbnails in HD quality',
  category: 'creative',
  icon: '📹',
  color: 'from-red-500 to-pink-500',
  url: '/tools/youtube-thumbnail',
  status: 'live',
  tags: ['youtube', 'thumbnail', 'download', 'video'],
  difficulty: 'Instant',
  timeToUse: '5 seconds',
  featured: true,
  new: true,
},
{
  id: 'gradient-generator',
  name: 'Gradient Generator',
  description: 'Create beautiful CSS gradients for web design',
  category: 'creative',
  icon: '🎨',
  color: 'from-purple-500 to-pink-500',
  url: '/tools/gradient-generator',
  status: 'live',
  tags: ['gradient', 'css', 'design', 'color', 'generator'],
  difficulty: 'Simple',
  timeToUse: '1 minute',
  featured: false,
  new: true,
  badge: 'NEW',
},
]