// app/lib/categories/creative-tools.ts
import type { Tool } from './types'

export const creativeTools: Tool[] = [
  {
    id: 'instagram-bio',
    name: 'Instagram Bio Generator',
    description: 'Create perfect profile bios that attract followers',
    category: 'creative',
    icon: '📱',
    color: 'from-pink-500 to-purple-600',
    status: 'live',
    url: '/tools/instagram-bio',
    tags: ['instagram', 'bio', 'social', 'profile', 'generator'],
    difficulty: 'Simple',
    timeToUse: '2 minutes',
    featured: true,
    new: true,
    badge: 'HOT',
  },
  {
    id: 'youtube-thumbnail',
    name: 'YouTube Thumbnail Downloader',
    description: 'Download video thumbnails in HD quality',
    category: 'creative',
    icon: '📹',
    color: 'from-red-500 to-pink-500',
    status: 'live',
    url: '/tools/youtube-thumbnail',
    tags: ['youtube', 'thumbnail', 'download', 'video'],
    difficulty: 'Instant',
    timeToUse: '5 seconds',
    featured: true,
    new: true,
  },
  {
    id: 'gradient-generator',
    name: 'Gradient Generator',
    description: 'Create beautiful CSS gradients for web design',
    category: 'creative',
    icon: '🎨',
    color: 'from-purple-500 to-pink-500',
    status: 'live',
    url: '/tools/gradient-generator',
    tags: ['gradient', 'css', 'design', 'color', 'generator'],
    difficulty: 'Simple',
    timeToUse: '1 minute',
    featured: false,
    new: true,
    badge: 'NEW',
  },
]
