// app/lib/categories/dev-tools.ts
import type { Tool } from './types'

export const devTools: Tool[] = [
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate MD5, SHA-256, SHA-512 hashes with HMAC support and verification.',
    category: 'dev-tools',
    icon: '🔐',
    color: 'from-green-500 to-teal-500',
    status: 'live',
    url: '/tools/hash-generator',
    tags: ['Hash', 'MD5', 'SHA-256', 'Security', 'Checksum', 'HMAC', 'developer'],
    difficulty: 'Instant',
    timeToUse: '5 seconds',
    featured: true,
    new: true,
    badge: 'NEW',
    pricing: 'free',
    dataProcessing: 'local',
    lastUpdated: '2025-12',
  },
  {
    id: 'code-dependency-visualizer',
    name: 'Code Dependency Visualizer',
    description: 'Analyze project structure and visualize file dependencies.',
    category: 'dev-tools',
    icon: '📊',
    color: 'from-blue-500 to-indigo-600',
    status: 'live',
    url: '/tools/code-dependency-visualizer',
    tags: ['Code Analysis', 'Dependencies', 'Visualization', 'developer'],
    difficulty: 'Intermediate',
    timeToUse: '2 minutes',
    featured: true,
    pricing: 'free',
    dataProcessing: 'local',
    dependencies: ['d3', '@babel/parser'],
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test and debug regular expressions with ReDoS detection and code generation.',
    category: 'dev-tools',
    icon: '🔤',
    color: 'from-orange-500 to-red-500',
    status: 'live',
    url: '/tools/regex-tester',
    tags: ['Regex', 'Testing', 'Pattern', 'developer', 'security'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: true,
    new: true,
    badge: 'NEW',
    pricing: 'free',
    dataProcessing: 'local',
    lastUpdated: '2025-12',
  },
  {
    id: 'code-formatter',
    name: 'Code Formatter',
    description: 'Format and beautify JSON, HTML, CSS, JavaScript code.',
    category: 'dev-tools',
    icon: '✨',
    color: 'from-sky-500 to-blue-500',
    status: 'live',
    url: '/tools/code-formatter',
    tags: ['code', 'format', 'beautify', 'minify', 'json', 'html', 'css', 'developer'],
    difficulty: 'Instant',
    timeToUse: '10 seconds',
    featured: true,
    new: true,
    badge: 'NEW',
    pricing: 'free',
    dataProcessing: 'local',
    lastUpdated: '2025-12',
  },
  {
    id: 'meta-tag-generator',
    name: 'Meta Tag Generator',
    description: 'Generate SEO meta tags with Open Graph and Twitter Cards.',
    category: 'dev-tools',
    icon: '🏷️',
    color: 'from-indigo-500 to-purple-500',
    status: 'live',
    url: '/tools/meta-tag-generator',
    tags: ['meta', 'seo', 'open-graph', 'twitter', 'html', 'developer'],
    difficulty: 'Simple',
    timeToUse: '1 minute',
    featured: true,
    new: true,
    badge: 'NEW',
    pricing: 'free',
    dataProcessing: 'local',
    lastUpdated: '2025-12',
  },
  {
    id: 'cron-generator',
    name: 'Cron Generator',
    description: 'Build and understand cron expressions with visual builder.',
    category: 'dev-tools',
    icon: '⏰',
    color: 'from-amber-500 to-orange-500',
    status: 'live',
    url: '/tools/cron-generator',
    tags: ['cron', 'schedule', 'crontab', 'timer', 'developer'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: true,
    new: true,
    badge: 'NEW',
    pricing: 'free',
    dataProcessing: 'local',
    lastUpdated: '2025-12',
  },
  {
    id: 'diff-checker',
    name: 'Diff Checker',
    description: 'Compare two texts and find differences with side-by-side view.',
    category: 'dev-tools',
    icon: '📊',
    color: 'from-violet-500 to-purple-500',
    status: 'live',
    url: '/tools/diff-checker',
    tags: ['diff', 'compare', 'text', 'code', 'developer'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: true,
    new: true,
    badge: 'NEW',
    pricing: 'free',
    dataProcessing: 'local',
    lastUpdated: '2025-12',
  },
]