// app/lib/categories/dev-tools.ts
import type { Tool } from './types'

export const devTools: Tool[] = [
  {
    id: 'markdown-html',
    name: 'Markdown to HTML',
    description: 'Convert Markdown to HTML with live preview. GitHub Flavored supported.',
    category: 'dev-tools',
    icon: '📄',
    emoji: '📄',
    color: 'from-gray-600 to-gray-800',
    status: 'live',
    url: '/tools/markdown-html',
    tags: ['markdown', 'html', 'converter', 'preview', 'developer'],
    difficulty: 'Simple',
    timeToUse: '10 seconds',
    featured: false,
    pricing: 'free',
    dataProcessing: 'local',
  },
  {
    id: 'json-csv',
    name: 'JSON to CSV Converter',
    description: 'Convert between JSON and CSV formats easily',
    category: 'dev-tools',
    icon: '🔄',
    color: 'from-purple-500 to-indigo-500',
    url: '/tools/json-csv',
    status: 'live',
    tags: ['json', 'csv', 'converter', 'data', 'api'],
    difficulty: 'Simple',
    timeToUse: '10 seconds',
    featured: false,
    new: true,
    badge: 'NEW',
  },
  {
    id: 'test-file-generator',
    name: 'Test File Generator',
    description: 'Generate custom test files with exact size and content specifications',
    category: 'dev-tools',
    icon: '📄',
    color: 'from-cyan-500 to-purple-500',
    status: 'live',
    url: '/tools/test-file-generator',
    tags: ['testing', 'files', 'pdf', 'development', 'upload', 'validation'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: false,
    new: true,
    apiRequired: false,
    pricing: 'free',
    dataProcessing: 'local',
    lastUpdated: '2025-10',
  },
  {
    id: 'favicon-generator',
    name: 'Favicon Generator',
    description: 'Create website icons in all required sizes',
    category: 'dev-tools',
    icon: '🌐',
    color: 'from-purple-500 to-indigo-500',
    url: '/tools/favicon-generator',
    status: 'live',
    tags: ['favicon', 'icon', 'website', 'generator'],
    difficulty: 'Simple',
    timeToUse: '1 minute',
    featured: false,
    new: true,
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder text for designs and mockups',
    category: 'dev-tools',
    icon: '📝',
    color: 'from-purple-500 to-indigo-500',
    url: '/tools/lorem-ipsum',
    status: 'live',
    tags: ['lorem', 'ipsum', 'text', 'placeholder', 'dummy'],
    difficulty: 'Instant',
    timeToUse: '5 seconds',
    featured: false,
    new: true,
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate unique identifiers for databases and APIs',
    category: 'dev-tools',
    icon: '🔑',
    color: 'from-purple-500 to-indigo-500',
    url: '/tools/uuid-generator',
    status: 'live',
    tags: ['uuid', 'guid', 'identifier', 'unique', 'generator'],
    difficulty: 'Instant',
    timeToUse: '1 second',
    featured: true,
    new: true,
    badge: 'HOT',
  },
  {
    id: 'base64',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode and decode Base64 strings. Text and file conversion.',
    category: 'dev-tools',
    icon: '🔐',
    emoji: '🔐',
    color: 'from-green-500 to-teal-500',
    status: 'live',
    url: '/tools/base64',
    tags: ['base64', 'encode', 'decode', 'converter', 'developer'],
    difficulty: 'Simple',
    timeToUse: '5 seconds',
    featured: false,
    pricing: 'free',
    dataProcessing: 'local',
  },
  {
    id: 'code-dependency-visualizer',
    name: 'Code Dependency Visualizer',
    description: 'Analyze project structure and visualize file dependencies.',
    category: 'dev-tools',
    icon: '🔍',
    color: 'from-blue-500 to-indigo-600',
    status: 'live',
    url: '/tools/code-dependency-visualizer',
    tags: ['Code Analysis', 'Dependencies', 'Visualization'],
    difficulty: 'Intermediate',
    timeToUse: '2 minutes',
    featured: true,
    pricing: 'free',
    dataProcessing: 'local',
    dependencies: ['d3', '@babel/parser'],
  },
  {
    id: 'code-roaster',
    name: 'Code Roaster',
    description: 'AI-powered code review tool with humor. Get roasted!',
    category: 'dev-tools',
    icon: '🔥',
    color: 'from-orange-500 to-red-500',
    status: 'live',
    url: '/tools/code-roaster',
    tags: ['code review', 'ai', 'debugging', 'learning'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: true,
    new: true,
    badge: 'AI',
    pricing: 'free',
    apiRequired: true,
    dataProcessing: 'server',
  },
  {
    id: 'tech-stack-analyzer',
    name: 'Tech Stack Analyzer',
    description: 'Compare frameworks and get AI-powered recommendations.',
    category: 'dev-tools',
    icon: '⚙️',
    color: 'from-green-500 to-emerald-600',
    status: 'live',
    url: '/tools/tech-stack-analyzer',
    tags: ['Frameworks', 'Planning', 'AI Analysis'],
    difficulty: 'Advanced',
    timeToUse: '5 minutes',
    featured: true,
    apiRequired: true,
    pricing: 'freemium',
    dataProcessing: 'hybrid',
  },
{
  id: 'test-text-generator',
  name: 'Test Text Generator',
  description: 'Generate dummy text for testing and development.',
  category: 'dev-tools',
  icon: '📝',
  color: 'from-green-500 to-emerald-500',
  status: 'live',
  url: '/tools/test-text-generator',
  tags: ['testing', 'text', 'generator', 'lorem ipsum', 'development'],
  difficulty: 'Instant',
  timeToUse: '10 seconds',
  featured: false,
  new: true,
  pricing: 'free',
  dataProcessing: 'local',
  lastUpdated: '2025-10'
},
  {
    id: 'network-checker',
    name: 'Network Checker',
    description: 'Find why devices can\'t connect. Simple network troubleshooting.',
    category: 'dev-tools',
    icon: '🌐',
    emoji: '🌐',
    color: 'from-cyan-500 to-blue-600',
    status: 'live',
    url: '/tools/network-checker',
    tags: ['network', 'troubleshoot', 'ip', 'connection', 'lan'],
    difficulty: 'Simple',
    timeToUse: '1 minute',
    featured: false,
    new: true,
    badge: 'NEW',
    pricing: 'free',
    dataProcessing: 'local',
    lastUpdated: '2025-10',
  },
  {
    id: 'test-image-generator',
    name: 'Test Image Generator',
    description: 'Generate test images with custom size and complexity.',
    category: 'dev-tools',
    icon: '🖼️',
    color: 'from-purple-500 to-pink-500',
    status: 'live',
    url: '/tools/test-image-generator',
    tags: ['testing', 'image', 'generator', 'development', 'compression'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: false,
    new: true,
    pricing: 'free',
    dataProcessing: 'local',
    lastUpdated: '2025-10',
  },
  {
    id: 'stack-recommender',
    name: 'Stack Recommender',
    description: 'Get AI-powered tech stack recommendations for your project.',
    category: 'dev-tools',
    icon: '🤖',
    color: 'from-violet-500 to-purple-600',
    status: 'live',
    url: '/tools/stack-recommender',
    tags: ['AI', 'Planning', 'Recommendations'],
    difficulty: 'Intermediate',
    timeToUse: '3 minutes',
    featured: false,
    new: true,
    apiRequired: true,
    pricing: 'freemium',
    dataProcessing: 'server',
  },
  {
    id: 'ai-project-visualizer',
    name: 'AI Project Visualizer',
    description: 'Transform file structure into AI-shareable diagrams.',
    category: 'dev-tools', // Moved from disabled 'ai-powered' category
    icon: '🗂️',
    emoji: '🌳',
    color: 'from-cyan-500 to-purple-500',
    status: 'live',
    url: '/tools/ai-project-visualizer',
    tags: ['visualization', 'AI', 'project', 'mermaid', 'diagram'],
    difficulty: 'Simple',
    timeToUse: '1 minute',
    featured: false,
    new: false,
    badge: "AI",
    pricing: 'free',
    dataProcessing: 'local',
    lastUpdated: '2025-10',
  },
  {
  id: 'pdf-test-generator',
  name: 'PDF Test Generator',
  description: 'Generate test PDFs for validating summarizers and parsers',
  category: 'dev-tools',
  icon: '📄',
  color: 'from-green-500 to-teal-500',
  status: 'live',
  url: '/tools/pdf-test-generator',
  tags: ['testing', 'pdf', 'generator', 'validation', 'development'],
  difficulty: 'Instant',
  timeToUse: '10 seconds',
  featured: false,
  new: true,
  pricing: 'free',
  dataProcessing: 'local',
  lastUpdated: '2025-10'
},
  {
    id: 'regex-builder',
    name: 'Regex Builder & Tester',
    description: 'Build and test regular expressions with real-time matching.',
    category: 'dev-tools',
    icon: '🔤',
    color: 'from-red-500 to-orange-500',
    status: 'coming',
    badge: 'COMING SOON',
    url: '/tools/regex-builder',
    tags: ['Regex', 'Testing', 'Pattern'],
    difficulty: 'Intermediate',
    timeToUse: '1 minute',
    featured: false,
    pricing: 'free',
    dataProcessing: 'local',
  },
  {
    id: 'api-tester',
    name: 'API Request Builder',
    description: 'Test REST APIs with custom headers, body, and auth.',
    category: 'dev-tools',
    icon: '🔌',
    color: 'from-teal-500 to-cyan-500',
    status: 'coming',
    badge: 'COMING SOON',
    url: '/tools/api-tester',
    tags: ['API', 'Testing', 'HTTP'],
    difficulty: 'Intermediate',
    timeToUse: '30 seconds',
    featured: false,
    pricing: 'free',
    dataProcessing: 'server',
  },
]
