// app/lib/categories/editors.ts
import type { Tool } from './types'

export const editors: Tool[] = [
  // 画像編集
  {
    id: 'image-compress',
    name: 'Image Compressor',
    description: 'Compress images without losing quality. JPEG, PNG, WebP supported.',
    category: 'editors',
    icon: '🗜️',
    emoji: '🗜️',
    color: 'from-orange-500 to-red-500',
    status: 'live',
    url: '/tools/image-compress',
    tags: ['image', 'compress', 'optimize', 'reduce', 'size', 'photo', 'picture'],
    difficulty: 'Simple',
    timeToUse: '20 seconds',
    featured: true,
    pricing: 'free',
    dataProcessing: 'local',
  },
  {
    id: 'image-grid-maker',
    name: 'Image Grid Maker',
    description: 'Create numbered image grids instantly. Auto-numbering included.',
    category: 'editors',
    icon: '🎨',
    emoji: '🔢',
    color: 'from-cyan-500 to-blue-500',
    status: 'live',
    url: '/tools/image-grid-maker',
    tags: ['image', 'grid', 'collage', 'layout', 'combine', 'privacy', 'photo'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: true,
    new: true,
    pricing: 'free',
    dataProcessing: 'local',
    lastUpdated: '2025-08',
  },
  {
    id: 'image-splitter',
    name: 'Image Splitter',
    description: 'Split long images for printing. A4, A5, B5 paper sizes supported.',
    category: 'editors',
    icon: '✂️',
    emoji: '📄',
    color: 'from-purple-500 to-pink-500',
    status: 'live',
    url: '/tools/image-splitter',
    tags: ['image', 'split', 'paper', 'print', 'A4', 'divide', 'privacy', 'photo'],
    difficulty: 'Simple',
    timeToUse: '20 seconds',
    featured: true,
    new: true,
    pricing: 'free',
    dataProcessing: 'local',
    lastUpdated: '2025-09',
  },
  {
    id: 'blurtap',
    name: 'BlurTap',
    description: 'Mask sensitive info in images with one click. Perfect for privacy.',
    category: 'editors',
    icon: '🔒',
    color: 'from-cyan-500 to-purple-500',
    status: 'live',
    url: '/tools/blurtap',
    tags: ['Privacy', 'Images', 'Security', 'blur', 'mask', 'sensitive', 'photo', 'picture'],
    difficulty: 'Instant',
    timeToUse: '10 seconds',
    featured: true,
    pricing: 'free',
    dataProcessing: 'local',
  },
  {
    id: 'color-palette',
    name: 'Color Palette Generator',
    description: 'Generate beautiful color palettes from images or custom schemes.',
    category: 'editors',
    icon: '🎨',
    emoji: '🎨',
    color: 'from-pink-500 to-rose-500',
    status: 'live',
    url: '/tools/color-palette',
    tags: ['color', 'palette', 'design', 'creative', 'generator', 'image', 'photo'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: false,
    pricing: 'free',
    dataProcessing: 'local',
  },

  // PDF編集
  {
    id: 'pdf-tools',
    name: 'PDF Tools - Pick 3',
    description: 'Choose 3 essential PDF tools. Rotate, merge, split, compress.',
    category: 'editors',
    icon: '📄',
    color: 'from-red-500 to-orange-500',
    status: 'live',
    url: '/tools/pdf-tools',
    tags: ['PDF', 'Documents', 'Privacy', 'edit', 'merge', 'split', 'rotate', 'compress'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: true,
    new: true,
    pricing: 'freemium',
    dataProcessing: 'local',
    dependencies: ['pdf-lib', 'pdfjs-dist'],
  },

  // 将来追加予定（コメントアウト）
  /*
  // 動画編集
  {
    id: 'video-compress',
    name: 'Video Compressor',
    description: 'Compress videos while maintaining quality',
    category: 'editors',
    icon: '🎬',
    tags: ['video', 'compress', 'movie', 'mp4', 'webm'],
    status: 'coming',
  },
  {
    id: 'subtitle-editor',
    name: 'Subtitle Editor',
    description: 'Add and edit subtitles for videos',
    category: 'editors',
    icon: '💬',
    tags: ['video', 'subtitle', 'caption', 'text', 'movie'],
    status: 'coming',
  },

  // 音声編集
  {
    id: 'audio-compress',
    name: 'Audio Compressor',
    description: 'Compress audio files without quality loss',
    category: 'editors',
    icon: '🎵',
    tags: ['audio', 'compress', 'mp3', 'wav', 'music'],
    status: 'coming',
  },
  */
]