// app/lib/categories/generators.ts
import type { Tool } from './types'

export const generators: Tool[] = [
  // セキュリティ生成
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Create strong, secure passwords instantly with customizable options.',
    category: 'generators',
    icon: '🔑',
    emoji: '🛡️',
    color: 'from-cyan-600 to-blue-600',
    status: 'live',
    url: '/tools/password-generator',
    tags: ['password', 'security', 'generator', 'random', 'strong-password', 'privacy'],
    difficulty: 'Instant',
    timeToUse: '5 seconds',
    featured: true,
    new: false,
    badge: 'HOT',
    apiRequired: false,
    pricing: 'free',
    dataProcessing: 'local',
    lastUpdated: '2025-01',
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate unique identifiers for databases and APIs',
    category: 'generators',
    icon: '🔑',
    color: 'from-purple-500 to-indigo-500',
    url: '/tools/uuid-generator',
    status: 'live',
    tags: ['uuid', 'guid', 'identifier', 'unique', 'generator'],
    difficulty: 'Instant',
    timeToUse: '1 second',
    featured: true,
    new: true,
    badge: 'HOT',
  },
  {
    id: 'qr-code',
    name: 'QR Code Generator',
    description: 'Generate QR codes for URLs, text, WiFi. Custom colors available.',
    category: 'generators',
    icon: '📱',
    emoji: '📱',
    color: 'from-purple-500 to-indigo-500',
    status: 'live',
    url: '/tools/qr-code',
    tags: ['qr', 'code', 'generator', 'barcode', 'scan'],
    difficulty: 'Simple',
    timeToUse: '15 seconds',
    featured: true,
    pricing: 'free',
    dataProcessing: 'local',
  },

  // テキスト生成
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder text for designs and mockups',
    category: 'generators',
    icon: '📝',
    color: 'from-purple-500 to-indigo-500',
    url: '/tools/lorem-ipsum',
    status: 'live',
    tags: ['lorem', 'ipsum', 'text', 'placeholder', 'dummy'],
    difficulty: 'Instant',
    timeToUse: '5 seconds',
    featured: false,
    new: true,
  },
  {
    id: 'hashtag-generator',
    name: 'Hashtag Generator',
    description: 'Generate perfect hashtags for social media instantly',
    category: 'generators',
    icon: '#️⃣',
    color: 'from-pink-500 to-purple-500',
    status: 'live',
    url: '/tools/hashtag-generator',
    tags: ['hashtag', 'social-media', 'instagram', 'twitter', 'marketing'],
    difficulty: 'Instant',
    timeToUse: '5 seconds',
    featured: true,
    new: true,
    badge: 'HOT',
  },
  {
    id: 'instagram-bio',
    name: 'Instagram Bio Generator',
    description: 'Create perfect profile bios that attract followers',
    category: 'generators',
    icon: '📱',
    color: 'from-pink-500 to-purple-600',
    status: 'live',
    url: '/tools/instagram-bio',
    tags: ['instagram', 'bio', 'social', 'profile', 'generator'],
    difficulty: 'Simple',
    timeToUse: '2 minutes',
    featured: true,
    new: true,
    badge: 'HOT',
  },

  // デザイン生成
  {
    id: 'favicon-generator',
    name: 'Favicon Generator',
    description: 'Create website icons in all required sizes',
    category: 'generators',
    icon: '🌐',
    color: 'from-purple-500 to-indigo-500',
    url: '/tools/favicon-generator',
    status: 'live',
    tags: ['favicon', 'icon', 'website', 'generator'],
    difficulty: 'Simple',
    timeToUse: '1 minute',
    featured: false,
    new: true,
  },
  {
    id: 'gradient-generator',
    name: 'Gradient Generator',
    description: 'Create beautiful CSS gradients for web design',
    category: 'generators',
    icon: '🎨',
    color: 'from-purple-500 to-pink-500',
    status: 'live',
    url: '/tools/gradient-generator',
    tags: ['gradient', 'css', 'design', 'color', 'generator'],
    difficulty: 'Simple',
    timeToUse: '1 minute',
    featured: false,
    new: true,
    badge: 'NEW',
  },

  // テスト用生成
  {
    id: 'test-file-generator',
    name: 'Test File Generator',
    description: 'Generate custom test files with exact size and content specifications',
    category: 'generators',
    icon: '📄',
    color: 'from-cyan-500 to-purple-500',
    status: 'live',
    url: '/tools/test-file-generator',
    tags: ['testing', 'files', 'pdf', 'development', 'upload', 'validation'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: false,
    new: true,
    apiRequired: false,
    pricing: 'free',
    dataProcessing: 'local',
    lastUpdated: '2025-10',
  },
  {
    id: 'test-text-generator',
    name: 'Test Text Generator',
    description: 'Generate dummy text for testing and development.',
    category: 'generators',
    icon: '📝',
    color: 'from-green-500 to-emerald-500',
    status: 'live',
    url: '/tools/test-text-generator',
    tags: ['testing', 'text', 'generator', 'lorem ipsum', 'development'],
    difficulty: 'Instant',
    timeToUse: '10 seconds',
    featured: false,
    new: true,
    pricing: 'free',
    dataProcessing: 'local',
    lastUpdated: '2025-10',
  },
  {
    id: 'test-image-generator',
    name: 'Test Image Generator',
    description: 'Generate test images with custom size and complexity.',
    category: 'generators',
    icon: '🖼️',
    color: 'from-purple-500 to-pink-500',
    status: 'live',
    url: '/tools/test-image-generator',
    tags: ['testing', 'image', 'generator', 'development', 'compression'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: false,
    new: true,
    pricing: 'free',
    dataProcessing: 'local',
    lastUpdated: '2025-10',
  },
  {
    id: 'pdf-test-generator',
    name: 'PDF Test Generator',
    description: 'Generate test PDFs for validating summarizers and parsers',
    category: 'generators',
    icon: '📄',
    color: 'from-green-500 to-teal-500',
    status: 'live',
    url: '/tools/pdf-test-generator',
    tags: ['testing', 'pdf', 'generator', 'validation', 'development'],
    difficulty: 'Instant',
    timeToUse: '10 seconds',
    featured: false,
    new: true,
    pricing: 'free',
    dataProcessing: 'local',
    lastUpdated: '2025-10',
  },

  // テンプレート生成
  {
    id: 'cornell-note',
    name: 'Cornell Note Generator',
    description: 'Create Cornell-style note templates. 58% better retention.',
    category: 'generators',
    icon: '📝',
    emoji: '📝',
    color: 'from-cyan-600 to-blue-600',
    status: 'live',
    url: '/tools/cornell-note',
    tags: ['notes', 'study', 'learning', 'education', 'cornell', 'template', 'printable', 'pdf'],
    difficulty: 'Instant',
    timeToUse: '30 seconds',
    featured: true,
    new: true,
    badge: 'NEW',
    apiRequired: false,
    pricing: 'free',
    dataProcessing: 'local',
    dependencies: ['jspdf'],
    lastUpdated: '2025-10',
  },

  // イベント生成
  {
    id: 'countdown-timer',
    name: 'Countdown Timer',
    description: 'Track important events and deadlines',
    category: 'generators',
    icon: '⏳',
    color: 'from-cyan-500 to-blue-500',
    url: '/tools/countdown-timer',
    status: 'live',
    tags: ['timer', 'countdown', 'events', 'deadline'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: false,
    new: true,
    badge: 'NEW',
  },
]