// app/lib/categories/image-tools.ts
import type { Tool } from './types'

export const imageTools: Tool[] = [
  // Background Eraser - NEW
  {
    id: 'bg-eraser',
    name: 'Background Eraser',
    description: 'Remove image backgrounds instantly with AI. 100% free, works in your browser.',
    category: 'image-tools',
    icon: '✨',
    emoji: '✂️',
    color: 'from-violet-500 to-purple-500',
    status: 'live',
    url: '/tools/bg-eraser',
    tags: ['background', 'remove', 'eraser', 'cutout', 'transparent', 'png', 'ai', 'photo', 'image'],
    difficulty: 'Instant',
    timeToUse: '5 seconds',
    featured: true,
    new: true,
    pricing: 'free',
    dataProcessing: 'local',
    lastUpdated: '2025-12',
  },

  // Image Compressor (migrated from editors)
  {
    id: 'image-compress',
    name: 'Image Compressor',
    description: 'Compress images without losing quality. JPEG, PNG, WebP supported.',
    category: 'image-tools',
    icon: '🗜️',
    emoji: '🗜️',
    color: 'from-orange-500 to-red-500',
    status: 'live',
    url: '/tools/image-compress',
    tags: ['image', 'compress', 'optimize', 'reduce', 'size', 'photo', 'picture'],
    difficulty: 'Simple',
    timeToUse: '20 seconds',
    featured: true,
    pricing: 'free',
    dataProcessing: 'local',
  },

  // Image Grid Maker (migrated from editors)
  {
    id: 'image-grid-maker',
    name: 'Image Grid Maker',
    description: 'Create numbered image grids instantly. Auto-numbering included.',
    category: 'image-tools',
    icon: '🎨',
    emoji: '🔢',
    color: 'from-cyan-500 to-blue-500',
    status: 'live',
    url: '/tools/image-grid-maker',
    tags: ['image', 'grid', 'collage', 'layout', 'combine', 'privacy', 'photo'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: true,
    pricing: 'free',
    dataProcessing: 'local',
    lastUpdated: '2025-08',
  },

  // Image Splitter (migrated from editors)
  {
    id: 'image-splitter',
    name: 'Image Splitter',
    description: 'Split long images for printing. A4, A5, B5 paper sizes supported.',
    category: 'image-tools',
    icon: '✂️',
    emoji: '📄',
    color: 'from-purple-500 to-pink-500',
    status: 'live',
    url: '/tools/image-splitter',
    tags: ['image', 'split', 'paper', 'print', 'A4', 'divide', 'privacy', 'photo'],
    difficulty: 'Simple',
    timeToUse: '20 seconds',
    featured: true,
    pricing: 'free',
    dataProcessing: 'local',
    lastUpdated: '2025-09',
  },

  // BlurTap (migrated from editors)
  {
    id: 'blurtap',
    name: 'BlurTap',
    description: 'Mask sensitive info in images with one click. Perfect for privacy.',
    category: 'image-tools',
    icon: '🔒',
    color: 'from-cyan-500 to-purple-500',
    status: 'live',
    url: '/tools/blurtap',
    tags: ['Privacy', 'Images', 'Security', 'blur', 'mask', 'sensitive', 'photo', 'picture'],
    difficulty: 'Instant',
    timeToUse: '10 seconds',
    featured: true,
    pricing: 'free',
    dataProcessing: 'local',
  },

  // Color Palette Generator (migrated from editors)
  {
    id: 'color-palette',
    name: 'Color Palette Generator',
    description: 'Generate beautiful color palettes from images or custom schemes.',
    category: 'image-tools',
    icon: '🎨',
    emoji: '🎨',
    color: 'from-pink-500 to-rose-500',
    status: 'live',
    url: '/tools/color-palette',
    tags: ['color', 'palette', 'design', 'creative', 'generator', 'image', 'photo'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: false,
    pricing: 'free',
    dataProcessing: 'local',
  },
]
