// app/lib/categories/quick-tools.ts
import type { Tool } from './types'

export const quickTools: Tool[] = [
  {
    id: 'pc-optimizer',
    name: 'PC Optimizer Advisor',
    description: 'Free up storage space! Analyze Program Files for removal.',
    category: 'quick-tools',
    icon: '💻',
    emoji: '💻',
    color: 'from-blue-500 to-cyan-500',
    status: 'live',
    url: '/tools/pc-optimizer',
    tags: ['Windows', 'Performance', 'Cleanup'],
    difficulty: 'Simple',
    timeToUse: '3 minutes',
    featured: true,
    new: true,
    pricing: 'free',
    dataProcessing: 'local',
    lastUpdated: '2025-01'
  },
  {
  id: 'password-generator',
  name: 'Password Generator',
  description: 'Create strong, secure passwords instantly with customizable options.',
  category: 'quick-tools',
  icon: '🔐',
  emoji: '🛡️',
  color: 'from-cyan-600 to-blue-600',
  status: 'live',
  url: '/tools/password-generator',
  tags: ['password', 'security', 'generator', 'random', 'strong-password', 'privacy'],
  difficulty: 'Instant',
  timeToUse: '5 seconds',
  featured: true,
  new: false,
  badge: 'HOT',
  apiRequired: false,
  pricing: 'free',
  dataProcessing: 'local',
  dependencies: [],
  configRequired: false,
  lastUpdated: '2025-01',
  projectSource: 'Security Tools Suite'
},
{
  id: 'age-calculator',
  name: 'Age Calculator',
  description: 'Calculate exact age in years, months, and days',
  category: 'quick-tools',
  icon: '🎂',
  color: 'from-cyan-500 to-blue-500',
  url: '/tools/age-calculator',
  status: 'live',
  tags: ['age', 'birthday', 'calculator', 'date'],
  difficulty: 'Instant',
  timeToUse: '5 seconds',
  featured: false,
  new: true,
  badge: 'NEW',
},
{
  id: 'bmi-calculator',
  name: 'BMI Calculator',
  description: 'Calculate Body Mass Index and health status',
  category: 'quick-tools',
  icon: '⚖️',
  color: 'from-cyan-500 to-blue-500',
  url: '/tools/bmi-calculator',
  status: 'live',
  tags: ['bmi', 'health', 'weight', 'calculator'],
  difficulty: 'Instant',
  timeToUse: '10 seconds',
  featured: false,
  new: true,
  badge: 'NEW',
},
{
  id: 'percentage-calculator',
  name: 'Percentage Calculator',
  description: 'Quick percentage calculations for any scenario',
  category: 'quick-tools',
  icon: '%',
  color: 'from-cyan-500 to-blue-500',
  url: '/tools/percentage-calculator',
  status: 'live',
  tags: ['percentage', 'calculator', 'math', 'discount'],
  difficulty: 'Instant',
  timeToUse: '5 seconds',
  featured: false,
  new: true,
},
{
  id: 'twitter-counter',
  name: 'Twitter Counter',
  description: 'Count characters for Twitter/X posts in real-time',
  category: 'quick-tools',
  icon: '🐦',
  color: 'from-cyan-500 to-blue-500',
  url: '/tools/twitter-counter',
  status: 'live',
  tags: ['twitter', 'x', 'character', 'counter', 'social'],
  difficulty: 'Instant',
  timeToUse: '1 second',
  featured: false,
  new: true,
},
{
  id: 'countdown-timer',
  name: 'Countdown Timer',
  description: 'Track important events and deadlines',
  category: 'quick-tools',
  icon: '⏳',
  color: 'from-cyan-500 to-blue-500',
  url: '/tools/countdown-timer',
  status: 'live',
  tags: ['timer', 'countdown', 'events', 'deadline'],
  difficulty: 'Simple',
  timeToUse: '30 seconds',
  featured: false,
  new: true,
  badge: 'NEW',
},
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert between various units of measurement instantly.',
    category: 'quick-tools',
    icon: '📏',
    emoji: '📏',
    color: 'from-green-500 to-emerald-500',
    status: 'live',
    url: '/tools/unit-converter',
    tags: ['convert', 'units', 'measurement', 'calculator'],
    difficulty: 'Simple',
    timeToUse: '10 seconds',
    featured: false,
    pricing: 'free',
    dataProcessing: 'local'
  },
  {
    id: 'text-counter',
    name: 'Text Counter',
    description: 'Count words, characters, sentences instantly for writers.',
    category: 'quick-tools',
    icon: '📝',
    emoji: '📝',
    color: 'from-blue-500 to-cyan-500',
    status: 'live',
    url: '/tools/text-counter',
    tags: ['text', 'counter', 'words', 'characters', 'writing'],
    difficulty: 'Instant',
    timeToUse: '5 seconds',
    featured: false,
    pricing: 'free',
    dataProcessing: 'local'
  },
  {
    id: 'qr-code',
    name: 'QR Code Generator',
    description: 'Generate QR codes for URLs, text, WiFi. Custom colors available.',
    category: 'quick-tools',
    icon: '📱',
    emoji: '📱',
    color: 'from-purple-500 to-indigo-500',
    status: 'live',
    url: '/tools/qr-code',
    tags: ['qr', 'code', 'generator', 'barcode', 'scan'],
    difficulty: 'Simple',
    timeToUse: '15 seconds',
    featured: true,
    pricing: 'free',
    dataProcessing: 'local'
  },
  {
    id: 'image-compress',
    name: 'Image Compressor',
    description: 'Compress images without losing quality. JPEG, PNG, WebP supported.',
    category: 'quick-tools',
    icon: '🗜️',
    emoji: '🗜️',
    color: 'from-orange-500 to-red-500',
    status: 'live',
    url: '/tools/image-compress',
    tags: ['image', 'compress', 'optimize', 'reduce', 'size'],
    difficulty: 'Simple',
    timeToUse: '20 seconds',
    featured: true,
    pricing: 'free',
    dataProcessing: 'local'
  },
  {
    id: 'color-palette',
    name: 'Color Palette Generator',
    description: 'Generate beautiful color palettes from images or custom schemes.',
    category: 'quick-tools',  // Moved from disabled 'creative' category
    icon: '🎨',
    emoji: '🎨',
    color: 'from-pink-500 to-rose-500',
    status: 'live',
    url: '/tools/color-palette',
    tags: ['color', 'palette', 'design', 'creative', 'generator'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: false,
    pricing: 'free',
    dataProcessing: 'local'
  },
  {
    id: 'blurtap',
    name: 'BlurTap',
    description: 'Mask sensitive info in images with one click. Perfect for privacy.',
    category: 'quick-tools',
    icon: '🔐',
    color: 'from-cyan-500 to-purple-500',
    status: 'live',
    url: '/tools/blurtap',
    tags: ['Privacy', 'Images', 'Security'],
    difficulty: 'Instant',
    timeToUse: '10 seconds',
    featured: true,
    pricing: 'free',
    dataProcessing: 'local'
  },
  {
    id: 'image-grid-maker',
    name: 'Image Grid Maker',
    description: 'Create numbered image grids instantly. Auto-numbering included.',
    category: 'quick-tools',
    icon: '🎨',
    emoji: '🔢',
    color: 'from-cyan-500 to-blue-500',
    status: 'live',
    url: '/tools/image-grid-maker',
    tags: ['image', 'grid', 'collage', 'layout', 'combine', 'privacy'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: true,
    new: true,
    pricing: 'free',
    dataProcessing: 'local',
    lastUpdated: '2025-01'
  },
  {
    id: 'image-splitter',
    name: 'Image Splitter',
    description: 'Split long images for printing. A4, A5, B5 paper sizes supported.',
    category: 'quick-tools',
    icon: '✂️',
    emoji: '📄',
    color: 'from-purple-500 to-pink-500',
    status: 'live',
    url: '/tools/image-splitter',
    tags: ['image', 'split', 'paper', 'print', 'A4', 'divide', 'privacy'],
    difficulty: 'Simple',
    timeToUse: '20 seconds',
    featured: true,
    new: true,
    pricing: 'free',
    dataProcessing: 'local',
    lastUpdated: '2025-01'
  },
  {
    id: 'pdf-tools',
    name: 'PDF Tools - Pick 3',
    description: 'Choose 3 essential PDF tools. Rotate, merge, split, compress.',
    category: 'quick-tools',
    icon: '📄',
    color: 'from-red-500 to-orange-500',
    status: 'live',
    url: '/tools/pdf-tools',
    tags: ['PDF', 'Documents', 'Privacy'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: true,
    new: true,
    pricing: 'freemium',
    dataProcessing: 'local',
    dependencies: ['pdf-lib', 'pdfjs-dist']
  },
  {
    id: 'json-format',
    name: 'JSON Beautify',
    description: 'Format, validate, and minify JSON data instantly.',
    category: 'quick-tools',
    icon: '{ }',
    emoji: '🔧',
    color: 'from-green-500 to-emerald-500',
    status: 'live',
    url: '/tools/json-format',
    tags: ['Data', 'Format', 'Quick'],
    difficulty: 'Instant',
    timeToUse: '5 seconds',
    featured: false,
    pricing: 'free',
    dataProcessing: 'local'
  },
  {
    id: 'text-case',
    name: 'Text Case Converter',
    description: 'Convert text between uppercase, lowercase, title case instantly.',
    category: 'quick-tools',
    icon: '🔤',
    color: 'from-pink-500 to-rose-500',
    status: 'live',
    url: '/tools/text-case',
    tags: ['Text', 'Format', 'Convert'],
    difficulty: 'Instant',
    timeToUse: '3 seconds',
    featured: false,
    pricing: 'free',
    dataProcessing: 'local'
  },
  {
    id: 'pdf-to-data',
    name: 'PDF to CSV/Excel',
    description: 'Extract tables from PDFs. AI-powered CSV or Excel conversion.',
    category: 'quick-tools',
    icon: '📊',
    emoji: '📊',
    color: 'from-emerald-500 to-teal-500',
    status: 'live',
    url: '/tools/pdf-to-data',
    tags: ['PDF', 'CSV', 'Excel', 'Data', 'AI', 'Extraction'],
    difficulty: 'Simple',
    timeToUse: '1 minute',
    featured: true,
    new: true,
    pricing: 'freemium',
    apiRequired: true,
    dataProcessing: 'server',
    dependencies: ['openai', 'xlsx'],
    lastUpdated: '2025-01'
  },
  {
    id: 'token-compressor',
    name: 'AI Token Compressor',
    description: 'Compress files for AI sharing. Reduce API costs by 70%.',
    category: 'quick-tools',
    icon: '🗜️',
    emoji: '💰',
    color: 'from-cyan-500 to-blue-600',
    status: 'live',
    url: '/tools/token-compressor',
    tags: ['token', 'compression', 'AI', 'optimization', 'ChatGPT', 'Claude'],
    difficulty: 'Simple',
    timeToUse: '2 minutes',
    featured: true,
    new: true,
    pricing: 'free',
    apiRequired: false,
    dataProcessing: 'local',
    lastUpdated: '2025-01',
    dependencies: ['tiktoken', 'jszip', 'file-saver']
  }
]