// app/lib/categories/study-tools.ts
import type { Tool } from './types'

export const studyTools: Tool[] = [
  {
    id: 'pdf-summarizer',
    name: 'PDF Summarizer',
    description: 'AI-powered PDF summary generator for quick study reviews.',
    category: 'study-tools',
    icon: '📄',
    color: 'from-green-500 to-teal-500',
    status: 'live',
    url: '/tools/pdf-summarizer',
    tags: ['pdf', 'summary', 'study', 'ai'],
    difficulty: 'Simple',
    timeToUse: '2 minutes',
    featured: true,
    new: true,
    pricing: 'freemium',
    apiRequired: true,
    dataProcessing: 'hybrid',
    dependencies: ['pdfjs-dist'],
  },
  {
    id: 'japanese-ocr',
    name: 'Japanese OCR & Translation',
    description: 'Extract and translate Japanese text from images instantly.',
    category: 'study-tools',
    icon: '🇯🇵',
    color: 'from-red-500 to-pink-500',
    status: 'live',
    url: '/tools/japanese-ocr',
    tags: ['ocr', 'japanese', 'translation', 'text-extraction', 'image-to-text'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: true,
    new: true,
    pricing: 'free',
    apiRequired: false,
    dataProcessing: 'local',
  },
  {
    id: 'debate-trainer',
    name: 'Debate Trainer',
    description: 'Practice argumentation skills with AI opponents. Get feedback.',
    category: 'study-tools',
    icon: '⚔️',
    emoji: '💬',
    color: 'from-purple-500 to-pink-500',
    status: 'live',
    url: '/tools/debate-trainer',
    tags: ['debate', 'argumentation', 'critical thinking', 'AI', 'practice'],
    difficulty: 'Intermediate',
    timeToUse: '15 minutes',
    featured: true,
    new: true,
    badge: 'AI',
    pricing: 'freemium',
    apiRequired: true,
    dataProcessing: 'server',
    dependencies: ['openai'],
    lastUpdated: '2025-01',
  },
  {
    id: 'ai-summarizer',
    name: 'AI Text Summarizer',
    description: 'Transform lengthy content into concise summaries with AI.',
    category: 'study-tools',
    icon: '✨',
    emoji: '📝',
    color: 'from-purple-500 to-pink-500',
    status: 'live',
    url: '/tools/ai-summarizer',
    tags: ['AI', 'Summary', 'Text', 'Study', 'Productivity'],
    difficulty: 'Simple',
    timeToUse: '30 seconds',
    featured: true,
    new: true,
    badge: 'AI',
    pricing: 'freemium',
    apiRequired: true,
    dataProcessing: 'server',
    lastUpdated: '2025-01',
  },
  {
    id: 'flashcard-maker',
    name: 'Flashcard Maker',
    description: 'Create smart flashcards from any text or PDF.',
    category: 'study-tools',
    icon: '🎴',
    emoji: '🎴',
    color: 'from-teal-500 to-green-500',
    status: 'coming',
    badge: 'COMING SOON',
    url: '/tools/flashcard-maker',
    tags: ['flashcards', 'study', 'memory', 'learning'],
    difficulty: 'Simple',
    timeToUse: '1 minute',
    featured: false,
    new: true,
    pricing: 'free',
    dataProcessing: 'local',
  },
  {
    id: 'study-planner',
    name: 'Study Planner',
    description: 'Generate personalized study schedules based on your goals.',
    category: 'study-tools',
    icon: '📅',
    color: 'from-emerald-500 to-teal-500',
    status: 'coming',
    badge: 'COMING SOON',
    url: '/tools/study-planner',
    tags: ['planning', 'schedule', 'productivity', 'study'],
    difficulty: 'Intermediate',
    timeToUse: '5 minutes',
    featured: false,
    new: false,
    pricing: 'free',
    dataProcessing: 'local',
  },
]
